ALTER TABLE users ALTER COLUMN id TYPE BIGINT;
ALTER TABLE products ALTER COLUMN id TYPE BIGINT;
ALTER TABLE orders ALTER COLUMN id TYPE BIGINT;
ALTER TABLE order_items ALTER COLUMN id TYPE BIGINT;

ALTER TABLE orders ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE order_items ALTER COLUMN order_id TYPE BIGINT;
ALTER TABLE order_items ALTER COLUMN product_id TYPE BIGINT;

